DROP TABLE IF EXISTS players;

CREATE TABLE players (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    position VARCHAR(512) NOT NULL,
    rank INTEGER NOT NULL  

);